[lab_directory_staff_loop label = true]
	[ld_photo]
	[ld_name_firstname]
	[ld_team]
	[ld_phd_link]
	[ld_hdr_link]
	[ld_function]
	[ld_mails]
	[ld_other_mails] 
	[ld_phone_number]
	[ld_social_link]
	[ld_fax_number]
	[ld_webpage]
	[ld_bio]
	<div class="clearfix"></div>
[/lab_directory_staff_loop]

